language: python
services:
  - docker
matrix:
  include:
    # case 1: run pfcon unit tests
    - python: "3.5"
      env: TO_TEST=pfcon
    # case 2: build pfcon and test integration with CUBE
    - dist: xenial
      env: TO_TEST=cube

install: 
  - if [ "$TO_TEST" = "pfcon" ]; then pip install .; fi

before_script:
  - if [ "$TO_TEST" = "cube" ]; then mv pman/CUBE_CI.sh CUBE_CI.sh; ./CUBE_CI.sh; fi

# command to run tests
script: 
  - if [ "$TO_TEST" = "pfcon" ];then nosetests; fi
  - if [ "$TO_TEST" = "cube" ]; then cd ../ChRIS_ultron_backEnd/; docker-compose exec chris_dev python manage.py test --tag integration; fi

notifications:
  slack: fnndsc:xcwPXeUGBBNRkwAlygS9gtCo