# https://docs.docker.com/compose/yml/
# Each service defined in docker-compose.yml must specify exactly one of
# image or build. Other keys are optional, and are analogous to their
# docker run command-line counterparts.
#
# As with docker run, options specified in the Dockerfile (e.g., CMD,
# EXPOSE, VOLUME, ENV) are respected by default - you don't need to
# specify them again in docker-compose.yml.
#

pfcon_dev:
  image:  ${CREPO}/pfcon:dev
  volumes:
    # - /var/run/docker.sock:/var/run/docker.sock
    - .:/usr/local/pfcon
  ports:
    - "5005:5005"
  labels:
    name: "PF controller, part of the CHRIS backend."
    role: "PF controller, part of the CHRIS backend."
  command: ["--forever", "--httpResponse"]
